name: JS Actions

on:
  pull_request:
    types: [labelled]

jobs:
  action:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      
    - name: hello-action
      uses: ./.github/actions/hello-world
      with:
        third-greeting: "Merlin"

    - name: ha-ha
      uses: ./.github/actions/joke-action
